project:
  type: website
  output-dir: _site

website:
  title: "Stan Q. He"
  site-url: "https://stanqhe.github.io"
  page-footer:
    left: "© 2026 Stan Q. He. All rights reserved."
    center: "[Terms of Use](/legal.html)"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 3
    smooth-scroll: true
    anchor-sections: false
    include-after-body:
      - toc-enhance.html
    respect-user-color-scheme: true