---
title: "起航新时代 我们正清辉｜2018 新年寄语"
description: "A keynote-like New Year piece, this article looks ahead to life as a long voyage through a new era. It frames the future as something vast, uncertain, and worth steering into with clarity, courage, and a strong sense of time."
author: "Stan H."
date: 2018-02-16
categories: Keynote
featured: false
---
当你看到晨间第一缕阳光，从水天相接的远方奔驰而来的时候，2018 年中国农历新春就已经到来了。新时代的朝阳已跃出地平线，正冉冉升起。

一年之计在于春，一日之计在于晨。

在这气温逐步攀升，暖风渐次吹拂的春日晨间，我们面朝大海，再次扬帆起航。

**新时代，新征程。**

**前方的征程是漫长的。**“路漫漫其修远兮，吾将上下而求索。”人生长路固漫漫，世间时光自永恒。漫长人生中，我们的年龄岁岁增长；永恒时光里，世界的纪年时时推进。岁于我同年于世，都是时间的节点。孔子十五志学，三十而立，直至七十从心所欲不逾矩中的每一个年龄都是时间节点；《上海 2035》城市总体规划报告中的每一个年份也都是时间节点······我们要善于把握人生中一个又一个重要的时间节点：如小升初、中考、高考、研究生入学考试、职业资格考试等；我们要知道在适当的年龄形成正确意识，以此来做正确的事：6 岁初入小学开始认真学习，12 岁遇见自己第一个本命年并直面竞争，18岁成年步入大学走出家庭走向社会并开始独当一面；我们还要关注身处环境的里程碑：家庭的特别纪念日（包括家庭成员的生日与结婚纪念日等），母校的校庆与其它名校的校庆日，中西方传统节日与纪念日，中国两个一百年奋斗目标中的年份，世界主要国家领导人换届时的年份，影响历史进程的重大事件发生的年份等······只有把握自己的年龄节点，关注环境的时间节点，我们才能将人生长路分段，让人生目标可期，从而讲好自己的「时间叙事」。

**前方的征程是广阔的。**“海阔凭鱼跃，天高任鸟飞。”大海无垠，航行方向任你选择。18 岁以前，你可以选择高考，在中国教育体系中沉浮十二年，通过高考踏入自己理想的高等学府；你也可以选择出国，接受异国的教育，体悟彼此之间的文化差异，并通过相应选拔制度踏入自己理想的高等学府。18 岁以后，你可以潜心学术，在自己擅长的垂直领域进行高精尖研究，在国际权威期刊上发表研究成果，攻克技术难题，取得重大突破，从而为所属领域做出自己的贡献；你可以涉足金融，在人与人物资交换的媒介场所观察企业、国家与世界经济的日常运作，总结过去表现，展望未来发展，为当下决策出谋划策，从而为所属实体做出自己的贡献；你也可以步入仕途，做大众的公仆，以百姓为本，为人民服务，在施展自己政治抱负的同时，为国家的美好发展绘制蓝图，为世界的福祉进步作出自己的贡献。无论你选择哪一条航道，都是在这世界中实现自己的人生价值，并最终为世界做出贡献。至于所做贡献几何，我们说天空广袤，任尔飞翔。

**前方的征程是未知的。**“盖将自其变者而观之，则天地曾不能以一瞬；自其不变者而观之，则物与我皆无尽也。”世间瞬息万变，唯其变者为不变。今天规划妥当的事情，可能下一秒就因先决因素的改变而无法落实；今天不曾想到的事情，可能下一刻就因未知因素的发生而突然袭来。正因为此，我们要果断抓住机遇，尽量在风云际会之时不留遗憾。不仅如此，即便是抓住了一个优质机遇，我们也会在将机遇转化为成果的阶段，不可避免地遇到艰难险阻。面对困难挫折甚至危险，唯有先知其难畏其险，后不怕难不惧险，方能鼓起勇气，把握航向，继续前进。

**新时代，新征程。**

纵使征途漫漫贯穿一生，航程四海浩瀚无边，更有汹涌波涛之险与电闪雷鸣之变，我们也不能跳船逃避或是在船上消极避世，因为这唯一的人生之舟早已起航，而船上唯一的乘客「 就是你 」。我们能做的，就是去握紧方向盘，正视前方，持续推进。我们把握现在，直面未来，以期在海上划出一道「 漂亮的涟漪 」。

“**新时代是奋斗者的时代**”，奋斗的篇章已经开启。出发吧，走，就有希望。

**Voyage2018 - Voice Your Age**

2018 年 2 月 16 日

农历戊戌年正月初一

于上海

::: {.article-endnote}

**注释**

1. 封面及篇末图片来源：2018 年度 LOGO —— Voyage2018  
2. Voyage *n.*〔C〕 航海；航行；旅行


**参考资料**

[1] 白岩松. 《地平线断想（代序）》 痛并快乐着. 长江文艺出版社, 2016-04.  
[2] 上海 2035 [《上海市城市总体规划（2017–2035 年）》](http://mp.weixin.qq.com/s?__biz=MjM5NTA5NzYyMA==&mid=2654028823&idx=1&sn=703e21c6e117c6241c98f67167b42cba&chksm=bd38596c8a4fd07af3844da81607c29fbfe68d83e4958af29bf68378d4805df67bbadecf5189&mpshare=1&scene=21&srcid=0220v0I9AFA3EKNZ4XIaoC13#wechat_redirect) 上海发布 2018-01-04  
[3] 央视评论员 [《启航新时代》](http://mp.weixin.qq.com/s?__biz=MTI0MDU3NDYwMQ==&mid=2656646023&idx=1&sn=3b56a331b492ffce6c467bf589dc9e2d&scene=21#wechat_redirect) 央视新闻 2018-02-16  

:::